name: Deploy
on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build tailwind
        run: "deno task tailwind"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "todo-deno-kv"
          entrypoint: "main.tsx"
          root: "."